language: node_js
node_js:
- '4'
- '4.2'
- '4.1'
- '4.0'
- iojs
deploy:
  provider: heroku
  api_key:
    secure: Qbg09SMoPEUsu0jqBxbCJbPuylzvMx52VmP+f85BPhTU937dlFtsycd4aCBvwhSId3k2SVJlGVXYK2j7yrz3qFRYo7DSsT2IFZzjKh7+NXQTT6Pq1BsOf6Ujax1qmGX7gd1zNn/zrQy0fOSWE+FG+KVIs2pQFd3BnpOi/pIWXjsNzYcKhGC+YjMacSmzj5BgdC7kMPaA322xDvGnESYP3rxC3Ifm0hGXQlJ83+O/6A2Sox4Yp+SDdU/B1dnZIovnUDZ9RV37cZzYk4ZGpno+fBUZLlnciaFwYrMLtJc/UKUSYTzVpGSuy0rH0ODjMmHIlupqzJM4Wo5l43WNOWGKTsLeEY41Y95W9iZmwBMnW5blDY7dVXCDoapVCBnPXcDQdvaevg8anvewKy3guvpyASf7MiyxiXsqyDEe7wMj1WrgV9TFwrjBn0tEMdB+rUtpZrtUEKF6PQz2ILZMZd8vfSZbP/i2uaIQoCW9reXl0lUdB5EvgzbCneHASjtigT0A+vaMKnHelYzzd9PRDjadturDBG9NfXaLthYqzR0dnk3QggekvriwYm6OXDyR0EdWqGu8JwhgzUCWbzg8NM7UBr4UzS1t1ARFyxVnsg89FgqYEiWMukRKwhdsvcCa05dwMamxhzYK/I2aFvRJbYu38lXnAGPXPkE0dZDdNAxw8Fs=
  on: master
  app: tarea-2-ppmiquel
