language: node_js
node_js:
- '4'
- '4.2'
- '4.1'
- '4.0'
- iojs
deploy:
  provider: heroku
  api_key:
    secure: jGiOO1pJXWfz5IgifRbRl4kvT11TdFzH/u3Axd+i06Z54Sl1bAB/ZWzYf0zOFiEQU3YgymH5veSZKrRCPjqpgD7BhNUBDMdhiL/owGcyJNGTjDNkb2pICfRbdTP62NlGZ6/bDEUsSdfd4rCvIh6O8npQNYQ/ufQDITG9b3jVrF1GiMRe7qaYFHmqOmMCfgufFoegQEXurRmUKiUx+2Q5/mgByBNTRMDWyJJSxDdDX6WL3biXYn+OBTyQdJOC8uZ1rPUwE5w8O34wG2CQitmGqQF9hJEFSmP1F+EFEtQheW2+6rfLAikdhZgnHUgZA8q/227DERLfWDM0sTwriwGdzwgruzmaRrMvzd0Mb+ms9RbHsgUzk94J2I11VIb96wv7blwCru1AWFUdOZIWVLFQOUnnTfbQyEJluHT3yvoTdF+LDIg+RuEWdflFUj823lC9hdmbttGLa8yHYMB7HpFeVFu4RNNxNq2sKKrl4217I7gkX2I+NnlDhAQXJ+bZgQ6bvVg0Spp00E0XBYz2x7V1yR/RFFU/GzBTsJNXRYbULNiwJCguZzb/lPHAtpkbKlqEEHmVJwYV52245IxbFBUtG+iF7nM3yrvBxwa1cbR6Nvx7KB2qcjMBMDXTWd+qM4+J3Hif2025HiSuUPXZoOGlxrXZiCQCxx2Kj8u1xEVItcc=
  on: master
  app: tarea-2-ppmiquel
